# Generated by Django 5.2.8 on 2025-12-01 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lost_Found', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('lost', 'Lost'), ('found', 'Found'), ('returned', 'Returned')], max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, help_text='11-digit Nigerian phone number (e.g., 08012345678)', max_length=11),
        ),
    ]
