# Generated by Django 5.2.8 on 2025-12-03 05:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lost_Found', '0002_alter_item_status_alter_user_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='location_found',
            new_name='current_location',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='location_lost',
            new_name='reward',
        ),
        migrations.AddField(
            model_name='item',
            name='location_building',
            field=models.CharField(default='item', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='location_details',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='date_occurred',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
