# Generated by Django 5.2.8 on 2025-12-03 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lost_Found', '0003_rename_location_found_item_current_location_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='current_location',
            new_name='location_found',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='reward',
            new_name='location_lost',
        ),
        migrations.RemoveField(
            model_name='item',
            name='location_building',
        ),
        migrations.RemoveField(
            model_name='item',
            name='location_details',
        ),
        migrations.AlterField(
            model_name='item',
            name='date_occurred',
            field=models.DateTimeField(),
        ),
    ]
